### ISSUE TITLE
unexpected token at 'Cannot GET /webpack/manifest.json

### ISSUE THREAD

**Issue by hazardco** [mipearson/webpack-rails#58]
Hello,

I have a problem with this gem. I have created a simple project to test webpack-rails with a controller and a unique view. When i execute foreman start I get the following error: "unexpected token at 'Cannot GET /webpack/manifest.json"

I have:
- Ruby 2.3.0
- Rails 5.0
- Node 6.6.0

I followed the installation instructions:

```
-Add webpack-rails to your gemfile
-Run bundle install to install the gem
-Run bundle exec rails generate webpack_rails:install to copy across example files
-Run foreman start to start webpack-dev-server and rails server at the same time
-Add the webpack entry point to your layout (see next section)
-Edit webpack/application.js and write some code
```

I have added "<%= javascript_include_tag *webpack_asset_paths("application") %>" to the layout.html.erb

¿Any solution?

Thanks!!

**Comment by mipearson** [comment]
A very recent new version of a dependency of webpack or webpack-dev-server is breaking manifest generation. I'm looking into this now.

**Comment by mipearson** [comment]
Workaround: add:
```
    "webpack-dev-middleware": "1.7.0"
```
to your package.json, run `npm install && npm dedup`

There seems to be an issue with stats-webpack-plugin & the latest version of webpack-dev-middleware.

**Comment by juanca** [comment]
Fixed in latest, see https://github.com/webpack/webpack-dev-middleware/pull/129

**Comment by wemmick** [comment]
I just installed this gem and am getting the same error: 

``` JSON::ParserError at /
784: unexpected token at 'Cannot GET /webpack/manifest.json
'
```

I'm on Rails 4.2.4, Ruby 2.2.2p95, Node 4.1.1

I tried adding the webpack-dev-middleware to my package.json dependencies, but am still getting the error.  Any ideas?  Or do you need more info from me?
